# Generated by Django 4.1.7 on 2023-10-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="meal_time",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
