# Generated by Django 4.1.7 on 2023-10-05 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_alter_studentwallet_student"),
        ("orders", "0003_temporaryorderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporaryorderitem",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="students.student",
            ),
        ),
    ]
