# Generated by Django 4.1.7 on 2023-10-05 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_alter_studentwallet_student"),
        ("orders", "0004_temporaryorderitem_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temporaryorderitem",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
    ]
