# Generated by Django 4.1.7 on 2023-10-10 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_alter_studentwallet_student"),
        ("orders", "0005_alter_temporaryorderitem_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studentorders",
                to="students.student",
            ),
        ),
    ]
