# Generated by Django 4.1.7 on 2023-10-17 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_menu_category"),
        ("orders", "0007_order_served_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryCustomerOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("quantity", models.FloatField(default=0)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "menu_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="inventory.menu"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
