# Generated by Django 4.1.7 on 2023-10-17 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_alter_studentwallet_student"),
        ("orders", "0008_temporarycustomerorderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="studentorders",
                to="students.student",
            ),
        ),
    ]
