# Generated by Django 4.1.7 on 2023-11-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0010_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Cancelled", "Cancelled"),
                    ("Processed", "Processed"),
                    ("Pending", "Pending"),
                    ("Nullified", "Nullified"),
                ],
                max_length=255,
            ),
        ),
    ]
