# Generated by Django 4.1.7 on 2023-11-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0011_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Mpesa", "Mpesa"),
                    ("Cash", "Cash"),
                    ("Wallet", "Wallet"),
                    ("Wallet And Cash", "Wallet And Cash"),
                    ("Wallet And Mpesa", "Wallet And Mpesa"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
