# Generated by Django 4.1.7 on 2023-11-25 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0021_alter_menu_updated_today"),
        ("orders", "0014_orderitem_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temporaryorderitem",
            name="menu_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.menu"
            ),
        ),
    ]
