# Generated by Django 4.1.7 on 2023-11-25 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0015_alter_temporaryorderitem_menu_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="user",
        ),
    ]
