# Generated by Django 5.1.7 on 2025-12-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0017_orderitem_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="month",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="year",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="month",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
