# Generated by Django 4.1.7 on 2023-10-18 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_alter_studentwallet_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletRechargeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "recharge_method",
                    models.CharField(
                        choices=[("Mpesa", "Mpesa"), ("Cash", "Cash")], max_length=255
                    ),
                ),
                (
                    "amount_recharged",
                    models.DecimalField(decimal_places=10, max_digits=10),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.student",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.studentwallet",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
