# Generated by Django 5.1.7 on 2025-12-29 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_quotagroup"),
        ("students", "0006_student_credit_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="quota_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.quotagroup",
            ),
        ),
    ]
