# Generated by Django 5.1.7 on 2026-01-01 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_student_quota_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="walletrechargelog",
            name="wallet",
        ),
        migrations.RemoveField(
            model_name="walletrechargelog",
            name="student",
        ),
        migrations.DeleteModel(
            name="StudentWallet",
        ),
        migrations.DeleteModel(
            name="WalletRechargeLog",
        ),
    ]
