# Generated by Django 4.1.7 on 2023-11-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_expense"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="payment_method",
            field=models.CharField(
                choices=[("Mpesa", "Mpesa"), ("Cash", "Cash")],
                max_length=255,
                null=True,
            ),
        ),
    ]
