# Generated by Django 5.1.7 on 2025-12-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_quotagroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="expense_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="month",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="year",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
