# Generated by Django 5.1.7 on 2026-01-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_expense_expense_date_expense_month_expense_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotagroup",
            name="student_type",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
