# Generated by Django 4.1.7 on 2023-09-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_gender_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="id_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
