# Generated by Django 4.1.7 on 2023-09-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_id_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("cashier", "Cashier"),
                    ("chef", "Chef"),
                    ("student", "Student"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
