# Generated by Django 4.1.7 on 2023-09-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("Kg", "Kg"),
                            ("Pieces", "Pieces"),
                            ("Boxes", "Boxes"),
                            ("Cartons", "Cartons"),
                            ("Metres", "Metres"),
                            ("Litres", "Litres"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
