# Generated by Django 4.1.7 on 2023-09-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="unit",
            field=models.CharField(
                choices=[
                    ("Kg", "Kg"),
                    ("Grams", "Grams"),
                    ("Pieces", "Pieces"),
                    ("Boxes", "Boxes"),
                    ("Cartons", "Cartons"),
                    ("Metres", "Metres"),
                    ("Litres", "Litres"),
                ],
                max_length=255,
            ),
        ),
    ]
