# Generated by Django 4.1.7 on 2023-10-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="added_to_cart",
            field=models.BooleanField(default=False),
        ),
    ]
