# Generated by Django 4.1.7 on 2023-10-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_menu_added_to_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="category",
            field=models.CharField(
                choices=[("drinks", "Drinks"), ("food", "Food"), ("fruits", "Fruits")],
                max_length=255,
                null=True,
            ),
        ),
    ]
