# Generated by Django 4.1.7 on 2023-10-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_menu_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="quantity",
            field=models.FloatField(default=0),
        ),
    ]
