# Generated by Django 4.1.7 on 2023-11-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_menu_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="starting_stock",
            field=models.FloatField(default=0),
        ),
    ]
