# Generated by Django 4.1.7 on 2023-11-21 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0012_inventory_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplies",
                to="inventory.supplier",
            ),
        ),
    ]
