# Generated by Django 4.1.7 on 2023-11-21 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0013_alter_inventory_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="amount_owed",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.CreateModel(
            name="SupplyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("item", models.CharField(max_length=255)),
                ("quantity_supplied", models.FloatField(default=0)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=200)),
                ("payment_method", models.CharField(max_length=255, null=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
