# Generated by Django 4.1.7 on 2023-11-21 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0015_supplylog_total_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplylog",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mysupplies",
                to="inventory.supplier",
            ),
        ),
    ]
