# Generated by Django 4.1.7 on 2023-11-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0017_supplylog_supply_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="total_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name="supplier",
            name="total_supplies_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
