# Generated by Django 4.1.7 on 2023-11-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0018_supplier_total_paid_supplier_total_supplies_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplylog",
            name="amount_due",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name="supplylog",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
