# Generated by Django 4.1.7 on 2023-11-22 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0019_supplylog_amount_due_supplylog_amount_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="updated_today",
            field=models.DateField(default=datetime.date(2023, 11, 22)),
        ),
    ]
