# Generated by Django 4.1.7 on 2023-11-22 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0020_menu_updated_today"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="updated_today",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
