# Generated by Django 5.1.7 on 2026-01-01 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0008_remove_walletrechargelog_wallet_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "total_spend_today",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studentwallet",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WalletRechargeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "recharge_method",
                    models.CharField(
                        choices=[("Mpesa", "Mpesa"), ("Cash", "Cash")], max_length=255
                    ),
                ),
                (
                    "amount_recharged",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.student",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wallets.studentwallet",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
