# Generated by Django 5.1.7 on 2025-12-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MpesaTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "merchant_request_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "checkout_request_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "response_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "customer_message",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("result_code", models.IntegerField()),
                ("result_desc", models.CharField(max_length=255)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "mpesa_receipt_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "transaction_date",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("status", models.CharField(default="Pending", max_length=20)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
