# Generated by Django 4.1.7 on 2023-11-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesreport",
            name="sold_or_spoiled",
            field=models.CharField(
                choices=[("Sold", "Sold"), ("Spoiled", "Spoiled")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="salesreport",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
    ]
