# Generated by Django 4.1.7 on 2023-11-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_salesreport_sold_or_spoiled_salesreport_total_cost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salesreport",
            name="total_cost",
        ),
        migrations.AddField(
            model_name="salesreport",
            name="quantity",
            field=models.FloatField(default=0),
        ),
    ]
