# Generated by Django 4.1.7 on 2023-11-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0006_remove_salesreport_payment_method_dailysalesreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesreport",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
