# Generated by Django 4.1.7 on 2023-11-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0007_salesreport_unit_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralisedReportData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("item", models.CharField(max_length=255, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "sold_or_spoiled",
                    models.CharField(
                        choices=[("Sold", "Sold"), ("Spoiled", "Spoiled")],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("quantity", models.FloatField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
