# Generated by Django 4.1.7 on 2023-11-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0010_dailysalesreportdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailysalesreportdata",
            name="date_recorded",
            field=models.DateField(null=True),
        ),
    ]
