# Generated by Django 5.1.7 on 2026-01-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0012_alter_dailysalesreportdata_date_recorded"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailysalesreport",
            name="month",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="dailysalesreport",
            name="year",
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="dailysalesreportdata",
            name="month",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="dailysalesreportdata",
            name="year",
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="generalisedreportdata",
            name="month",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="generalisedreportdata",
            name="year",
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="salesreport",
            name="month",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="salesreport",
            name="year",
            field=models.CharField(max_length=4, null=True),
        ),
    ]
